nguage: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t adityasri993/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adityasri993/docker-react npm run test
